### ISSUE TITLE
Create How section in Readme

### ISSUE THREAD

**Issue by ZooeyMiller** [dwyl/learn-seo#12]
Once we've explained why SEO is important, and what it is, we need to let the people reading this tutorial know how to actually do it on their site! 

we need to flesh out a `how` section with some explanation of basic SEO techniques and ideas, and once that's done we can look into expanding it with more awesome info.

**Comment by iteles** [comment]
👍 Looking good @ZooeyMiller @finnhodgkin , thanks!
