### ISSUE TITLE
Research SEO

### ISSUE THREAD

**Issue by ZooeyMiller** [dwyl/learn-seo#2]
both @finnhodgkin and I have minimal experience with SEO so we need to do a spike to get to grips with what it is and how to do it.

**Comment by finnhodgkin** [comment]
https://moz.com/beginners-guide-to-seo/how-search-engines-operate - great introduction to SEO and the differences between the major search engines :sparkles:

**Comment by ZooeyMiller** [comment]
Great quote from chapter 3 of the intro to SEO @finnhodgkin linked
> websites compete for attention and placement in the search engines, and those with the knowledge and experience to improve their website's ranking will receive the benefits of increased traffic and visibility.

**Comment by ZooeyMiller** [comment]
Some of the main takeaways from the research are:
#### Why? 
The majority of the way sites are found on the web is via search engines. There is a small amount of traffic from social media and people sharing sites, but largely traffic comes from search engines. 

Sites in the top 3 results for a search receive the most traffic, with the rest on the first page of the search receiving the next most, and those on pages other than the first receiving significantly less traffic. Thus, making your site as search engine friendly as possible, so that it is likely to come up in, as a minimum, the first 10 results for a search will greatly increase the traffic that your site receives. 

People also favour sponsored results far less than highly ranking results which come up naturally, so paying to have your site on the first page does not help, SEO is the way to go.

#### What? 

SEO is making sure that your website shows as highly as possible in search engine (Google, bing, yahoo) results for queries relevant to your site. Usually you will consider which kinds of queries you want to target and make sure that your site ranks highly for those queries. 

#### How?
- Don't have content hidden in Javascript, have as much in the html as possible. 
- Make sure the title of the page accurately represents the page
- Make sure all images have relevant alt text
- Make all content on the site accessible from links, not just through a search function
- Don't have search engine relevant content hidden behind forms (crawl robots don't submit forms)
- Have URLs for pages contain keywords about those pages

**Comment by ZooeyMiller** [comment]
@finnhodgkin and I have finished up with initial research, so closing this issue.
