### ISSUE TITLE
How search works

### ISSUE THREAD

**Issue by ZooeyMiller** [dwyl/learn-seo#9]
Great video from Google about how the search works, could be good to include to give a basic overview of how searches work, before we get into how to do SEO. 

https://www.youtube.com/watch?v=BNHR6IQJGZs

**Comment by ZooeyMiller** [comment]
Included in https://github.com/dwyl/learn-seo/pull/7/commits/51923a98c6f1e855e105f4a89e768302c735f040

**Comment by iteles** [comment]
👍  Now in `master`
